spring.application.name=Asistente

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bdasistente
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración Telegram Bot
bot.token=${TELEGRAM_BOT_TOKEN}
bot.username=${TELEGRAM_BOT_NAME}

# Configuración Groq IA
groq.api.key=${GROQ_API_KEY}
